version: '3.2'
services:
  # this is the web application we are going to test
  web:
    container_name: frontend
    image: cypress-react-frontend:3.0
    ports:
      - "3000:3000"
    networks:
      - brige_network
    environment:
      NPM_TOKEN: ${NPM_TOKEN}

  # Cypress container
  cypress:
    container_name: cypress
    image: cypress/included:5.6.0
    depends_on:
      - web
    networks:
      - brige_network
    environment:
      CYPRESS_baseUrl: http://frontend:3000
      NPM_TOKEN: ${NPM_TOKEN}   
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e

networks:
  brige_network:
    driver: bridge